### ISSUE TITLE
Can't get the classnames to line up correctly

### ISSUE THREAD

**Issue by jcreamer898** [StevenIseki/react-router-redux-example#1]
Love this example repository.

I'm trying to set my own up, but can't seem to shake this checksum error.

![](http://d.pr/i/16YwK+)

I have `cmrh.conf.js` with...

``` js
module.exports = {
  generateScopedName: "[name]__[local]___[hash:base64:5]",
};
```

And in my `webpack.config`...

``` js
loader: ExtractTextPlugin.extract("style", "css?modules&localIdentName=[name]_[local]__[hash:base64:5]"),
```

Any ideas?

Thanks!

**Comment by StevenIseki** [comment]
I think you have to make sure you are using the css-modules-require-hook/preset as in the [server.js](https://github.com/StevenIseki/react-router-redux-example/blob/master/server.js)

`require('css-modules-require-hook/preset');`

This should work okay and when I clone and run the repo I don't have an issue at the moment. Did you make any updates or is it just running it on first clone?

The usage for css modules require hook is as documented in sullenor's [demo](https://github.com/css-modules/css-modules-require-hook/tree/master/demo) hope this helps

**Comment by jcreamer898** [comment]
I tried to retro fit an app I'm working on with it and can't quite get it. I tried the preset and can't quite get the class names to match. 



On Wed, Mar 16, 2016 at 7:19 PM -0700, "Steven Iseki Martin" <notifications@github.com> wrote:












I think you have to make sure you are using the css-modules-require-hook/preset as in the server.js



require('css-modules-require-hook/preset');



This should work okay and when I clone and run the repo I don't have an issue at the moment. Did you make any updates or is it just running it on first clone?



The usage for css modules require hook is as documented in sullenor's demo hope this helps

**Comment by StevenIseki** [comment]
just another note as I do remember running into this issue when I set up this example. I needed to ensure  I had the [cmrh.conf.js](https://github.com/StevenIseki/react-router-redux-example/blob/master/cmrh.conf.js) file defined in the project, although I was not sure why.
It does look like the css loader is defined differently in yours, otherwise not sure what else might be different in your setup.

**yours**
loader: ExtractTextPlugin.extract("style", "css?modules&localIdentName=[name]_[local]__[hash:base64:5]"),

**mine:**
loader: ExtractTextPlugin.extract('style', `css?modules&localIdentName=[name]_[local]__[hash:base64:5]!postcss`),

**Comment by StevenIseki** [comment]
This is on the older version, should be working fine now.
